#!/bin/bash
cd $(git rev-parse --show-toplevel)
echo "Running post-commit"
if [ -e ".commit"]
    then
        echo "Found .commit, adding snapshot"
        snapshot/take_snapshot.py
        git add snapshot/
        git commit --amend -C HEAD --no-verify
        rm .commit
fi